# Generated by Django 6.0.3 on 2026-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearing_status',
            field=models.CharField(choices=[('hearing', 'Слышащий'), ('hard', 'Слабослышащий'), ('deaf', 'Глухой')], db_index=True, default='hearing', max_length=20, verbose_name='Статус слуха'),
        ),
    ]
