# Generated by Django 6.0.3 on 2026-07-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GestureLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Жестовая лемма',
                'verbose_name_plural': 'Жестовые леммы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GestureRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/gestures/')),
                ('gif', models.FileField(upload_to='gif/gestures/')),
                ('gif_mini', models.FileField(upload_to='gif/gestures/mini/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('moderation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_realizations', to=settings.AUTH_USER_MODEL)),
                ('gesture_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_realizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реализация жеста',
                'verbose_name_plural': 'Реализации жестов',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание значения')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Значение (денотат)',
                'verbose_name_plural': 'Значения (денотаты)',
            },
        ),
        migrations.CreateModel(
            name='TextLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('slug', models.SlugField(unique=True)),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Текстовая лемма',
                'verbose_name_plural': 'Текстовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='LexemeTriplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='dictionary.category', verbose_name='Категории')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_triplets', to=settings.AUTH_USER_MODEL)),
                ('gesture_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triplets', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triplets', to='dictionary.meaning', verbose_name='Значение')),
                ('text_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triplets', to='dictionary.textlexeme', verbose_name='Текстовая лемма')),
            ],
            options={
                'verbose_name': 'Триплет (текст-значение-жест)',
                'verbose_name_plural': 'Триплеты',
                'indexes': [models.Index(fields=['text_lexeme'], name='dictionary__text_le_1fbd8d_idx'), models.Index(fields=['gesture_lexeme'], name='dictionary__gesture_50b8e6_idx'), models.Index(fields=['meaning'], name='dictionary__meaning_d94285_idx')],
                'unique_together': {('text_lexeme', 'meaning', 'gesture_lexeme')},
            },
        ),
    ]
