# Generated by Django 6.0.3 on 2026-03-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestureLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
            ],
            options={
                'verbose_name': 'Жестовая лемма',
                'verbose_name_plural': 'Жестовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GestureRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/gestures/')),
                ('gif', models.FileField(upload_to='gif/gestures/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('moderation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Реализация жеста',
                'verbose_name_plural': 'Реализации жестов',
            },
        ),
        migrations.CreateModel(
            name='LexemeMeaningMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme_id', models.PositiveIntegerField()),
                ('is_auto_meaning', models.BooleanField(default=True, verbose_name='Создано автоматически')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное значение')),
            ],
            options={
                'verbose_name': 'Связь лемма-значение',
                'verbose_name_plural': 'Связи лемма-значение',
            },
        ),
        migrations.CreateModel(
            name='LexemePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_meaning', models.BooleanField(default=True, help_text='Автоматически созданное значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь текст<-->жест',
                'verbose_name_plural': 'Связи текст<-->жест',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание значения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Значение (денотат)',
                'verbose_name_plural': 'Значение (денотаты)',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TextLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
            ],
            options={
                'verbose_name': 'Текстовая лемма',
                'verbose_name_plural': 'Текстовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
    ]
