# Generated by Django 6.0.3 on 2026-04-30 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GestureLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('slug', models.SlugField(unique=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Жестовая лемма',
                'verbose_name_plural': 'Жестовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GestureRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/gestures/')),
                ('gif', models.FileField(upload_to='gif/gestures/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('moderation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_realizations', to=settings.AUTH_USER_MODEL)),
                ('gesture_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_realizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реализация жеста',
                'verbose_name_plural': 'Реализации жестов',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание значения')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Значение (денотат)',
                'verbose_name_plural': 'Значение (денотаты)',
            },
        ),
        migrations.AddField(
            model_name='gesturelexeme',
            name='meanings',
            field=models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Значения'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TextLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('slug', models.SlugField(unique=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
                ('meanings', models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Значения')),
            ],
            options={
                'verbose_name': 'Текстовая лемма',
                'verbose_name_plural': 'Текстовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='LexemePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gesture_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма')),
                ('text_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='dictionary.textlexeme', verbose_name='Текстовая лемма')),
            ],
            options={
                'verbose_name': 'Связь текст<-->жест',
                'verbose_name_plural': 'Связи текст<-->жест',
            },
        ),
        migrations.CreateModel(
            name='LexemeMeaningMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme_id', models.PositiveIntegerField()),
                ('is_auto_meaning', models.BooleanField(default=True, verbose_name='Создано автоматически')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное значение')),
                ('lexeme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning')),
            ],
            options={
                'verbose_name': 'Связь лемма-значение',
                'verbose_name_plural': 'Связи лемма-значение',
                'indexes': [models.Index(fields=['lexeme_type', 'lexeme_id'], name='dictionary__lexeme__117a2d_idx')],
                'unique_together': {('lexeme_type', 'lexeme_id', 'meaning')},
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучаю'), ('learned', 'Выучено')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('lexeme_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexemepair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'lexeme_pair')},
            },
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['text_lexeme'], name='dictionary__text_le_a6d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['gesture_lexeme'], name='dictionary__gesture_438a5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lexemepair',
            unique_together={('text_lexeme', 'gesture_lexeme')},
        ),
    ]
