# Generated by Django 6.0.3 on 2026-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexemepair',
            name='categories',
            field=models.ManyToManyField(to='dictionary.category', verbose_name='Категории'),
        ),
    ]
