# Generated by Django 6.0.3 on 2026-06-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personal',
            name='lexeme_pair',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
