# Generated by Django 6.0.3 on 2026-07-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexemetriplet',
            name='meaning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triplets', to='dictionary.meaning', verbose_name='Значение'),
        ),
    ]
