# Generated by Django 6.0.3 on 2026-03-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturelexeme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='gesturelexeme',
            name='categories',
            field=models.ManyToManyField(to='dictionary.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='gesturerealization',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_realizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gesturerealization',
            name='gesture_lexeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма'),
        ),
        migrations.AddField(
            model_name='gesturerealization',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_realizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lexememeaningmapping',
            name='lexeme_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lexemepair',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lexemepair',
            name='gesture_lexeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='dictionary.gesturelexeme', verbose_name='Жестовая лемма'),
        ),
        migrations.AddField(
            model_name='meaning',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='lexemepair',
            name='meaning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_pairs', to='dictionary.meaning', verbose_name='Смысл'),
        ),
        migrations.AddField(
            model_name='lexememeaningmapping',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning'),
        ),
        migrations.AddField(
            model_name='gesturelexeme',
            name='meanings',
            field=models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Значения'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textlexeme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='textlexeme',
            name='categories',
            field=models.ManyToManyField(to='dictionary.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='textlexeme',
            name='meanings',
            field=models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Значения'),
        ),
        migrations.AddField(
            model_name='lexemepair',
            name='text_lexeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='dictionary.textlexeme', verbose_name='Текстовая лемма'),
        ),
        migrations.AddIndex(
            model_name='lexememeaningmapping',
            index=models.Index(fields=['lexeme_type', 'lexeme_id'], name='dictionary__lexeme__117a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lexememeaningmapping',
            unique_together={('lexeme_type', 'lexeme_id', 'meaning')},
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['text_lexeme'], name='dictionary__text_le_a6d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['gesture_lexeme'], name='dictionary__gesture_438a5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lexemepair',
            unique_together={('text_lexeme', 'gesture_lexeme')},
        ),
    ]
