# Generated by Django 6.0.3 on 2026-03-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gesturecomposeitem',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='gesturecomposeitem',
            name='dictionary__compose_abfd4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='gesturecomposeitem',
            name='dictionary__gesture_f2c564_idx',
        ),
        migrations.RemoveField(
            model_name='gesturelexemecompose',
            name='items',
        ),
        migrations.RemoveField(
            model_name='gesturelexemecompose',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gesturelexemecompose',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='gesturelexemecompose',
            name='meanings',
        ),
        migrations.AlterUniqueTogether(
            name='textcomposeitem',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='textcomposeitem',
            name='dictionary__compose_e6d538_idx',
        ),
        migrations.RemoveIndex(
            model_name='textcomposeitem',
            name='dictionary__text_le_e27719_idx',
        ),
        migrations.RemoveField(
            model_name='textlexemecompose',
            name='items',
        ),
        migrations.RemoveField(
            model_name='textlexemecompose',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textlexemecompose',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='textlexemecompose',
            name='meanings',
        ),
        migrations.AlterField(
            model_name='gesturelexeme',
            name='text',
            field=models.CharField(max_length=200, unique=True, verbose_name='Текст / Жест'),
        ),
        migrations.AlterField(
            model_name='gesturerealization',
            name='lexeme_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['gesturelexeme', 'gesturelexemecompose']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='lexemepair',
            name='gesture_lexeme_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['gesturelexeme', 'gesturelexemecompose']}, on_delete=django.db.models.deletion.CASCADE, related_name='gesture_pairs', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='lexemepair',
            name='text_lexeme_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['textlexeme', 'textlexemecompose']}, on_delete=django.db.models.deletion.CASCADE, related_name='text_pairs', to='contenttypes.contenttype'),
        ),
        migrations.RemoveField(
            model_name='gesturecomposeitem',
            name='compose',
        ),
        migrations.RemoveField(
            model_name='gesturecomposeitem',
            name='gesture_lexeme',
        ),
        migrations.RemoveField(
            model_name='textcomposeitem',
            name='compose',
        ),
        migrations.RemoveField(
            model_name='textcomposeitem',
            name='text_lexeme',
        ),
        migrations.DeleteModel(
            name='GestureLexemeCompose',
        ),
        migrations.DeleteModel(
            name='GestureComposeItem',
        ),
        migrations.DeleteModel(
            name='TextLexemeCompose',
        ),
        migrations.DeleteModel(
            name='TextComposeItem',
        ),
    ]
