# Generated by Django 6.0.3 on 2026-04-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_lexemepair_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesturelexeme',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='textlexeme',
            name='categories',
        ),
    ]
