# Generated by Django 6.0.3 on 2026-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesturelexeme',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='textlexeme',
            name='is_published',
        ),
        migrations.AddField(
            model_name='gesturelexeme',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='textlexeme',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
