# Generated by Django 6.0.3 on 2026-03-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_gesturecomposeitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturerealization',
            name='gif',
            field=models.FileField(blank=True, upload_to='gif/gestures/'),
        ),
    ]
