# Generated by Django 6.0.3 on 2026-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_gesturelexeme_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturerealization',
            name='gif_mini',
            field=models.FileField(null=True, upload_to='gif/gestures/mini/'),
        ),
    ]
