# Generated by Django 6.0.3 on 2026-03-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_gesturerealization_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesturerealization',
            name='gif',
            field=models.FileField(upload_to='gif/gestures/'),
        ),
    ]
