# Generated by Django 6.0.3 on 2026-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_gesturelexeme_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
