# Generated by Django 6.0.3 on 2026-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_gesturerealization_gif_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesturerealization',
            name='gif_mini',
            field=models.FileField(upload_to='gif/gestures/mini/'),
        ),
    ]
