# Generated by Django 6.0.3 on 2026-03-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_meaning_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexemepair',
            name='is_auto_meaning',
        ),
        migrations.RemoveField(
            model_name='lexemepair',
            name='meaning',
        ),
    ]
