# Generated by Django 6.0.3 on 2026-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_remove_lexemepair_is_auto_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexemepair',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
