# Generated by Django 6.0.3 on 2026-03-29 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dictionary', '0006_lexemepair_moderation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучаю'), ('learned', 'Выучено'), ('hard', 'Сложный')], default='new', max_length=20, verbose_name='Статус изучения')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Процент изучения (0-100)', verbose_name='Прогресс (%)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('practice_count', models.PositiveIntegerField(default=0, verbose_name='Практик')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('learned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изучения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_dictionary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в личном словаре',
                'verbose_name_plural': 'Личный словарь',
                'ordering': ['-is_favorite', '-priority', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучаю'), ('learned', 'Выучено'), ('hard', 'Сложный')], default='new', max_length=20, verbose_name='Статус')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_entries', to='dictionary.meaning', verbose_name='Значение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_meanings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненный смысл',
                'verbose_name_plural': 'Сохраненные смыслы',
                'ordering': ['-is_favorite', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('target_count', models.PositiveIntegerField(verbose_name='Целевое количество')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=20, verbose_name='Период')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель изучения',
                'verbose_name_plural': 'Цели изучения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Количество элементов')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('items_studied', models.ManyToManyField(blank=True, to='dictionary.personaldictionary', verbose_name='Изученные элементы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия изучения',
                'verbose_name_plural': 'Сессии изучения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personaldictionary',
            index=models.Index(fields=['user', 'status'], name='dictionary__user_id_fdde02_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldictionary',
            index=models.Index(fields=['user', 'is_favorite'], name='dictionary__user_id_2427f1_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldictionary',
            index=models.Index(fields=['content_type', 'object_id'], name='dictionary__content_3c83a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personaldictionary',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='personalmeaning',
            unique_together={('user', 'meaning')},
        ),
    ]
