# Generated by Django 6.0.3 on 2026-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_personaldictionary_personalmeaning_studygoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldictionary',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
