# Generated by Django 6.0.3 on 2026-03-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_personaldictionary_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaldictionary',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='personaldictionary',
            name='dictionary__user_id_fdde02_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaldictionary',
            name='dictionary__user_id_2427f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaldictionary',
            name='dictionary__content_3c83a0_idx',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='items_studied',
        ),
        migrations.RemoveField(
            model_name='studygoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldictionary',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='personaldictionary',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalMeaning',
        ),
        migrations.DeleteModel(
            name='StudyGoal',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
        migrations.DeleteModel(
            name='PersonalDictionary',
        ),
    ]
