# Generated by Django 6.0.3 on 2026-03-15 18:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hearing_status', models.CharField(choices=[('hearing', 'Слышащий'), ('hard_of_hearing', 'Слабослышащий'), ('deaf', 'Глухой')], default='hearing', max_length=20, verbose_name='Статус слуха')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('native', 'Носитель РЖЯ'), ('linguist', 'Лингвист'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GestureLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/gestures/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Жестовая лемма',
                'verbose_name_plural': 'Жестовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GestureComposeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('gesture_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gesturelexeme')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='GestureLexemeCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
                ('items', models.ManyToManyField(related_name='compose_set', through='dictionary.GestureComposeItem', to='dictionary.gesturelexeme')),
            ],
            options={
                'verbose_name': 'Сочетание жестов',
                'verbose_name_plural': 'Сочетания жестов',
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='gesturecomposeitem',
            name='compose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compose_items', to='dictionary.gesturelexemecompose'),
        ),
        migrations.CreateModel(
            name='GestureRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme_id', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='videos/gestures/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('moderation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_realizations', to=settings.AUTH_USER_MODEL)),
                ('lexeme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_realizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реализация жеста',
                'verbose_name_plural': 'Реализации жестов',
            },
        ),
        migrations.CreateModel(
            name='LexemePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_lexeme_id', models.PositiveIntegerField()),
                ('gesture_lexeme_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_meaning', models.BooleanField(default=True, help_text='Автоматически созданный смысл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gesture_lexeme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_pairs', to='contenttypes.contenttype')),
                ('text_lexeme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_pairs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Связь текст<-->жест',
                'verbose_name_plural': 'Связи текст<-->жест',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание смысла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Смысл (денотат)',
                'verbose_name_plural': 'Смыслы (денотаты)',
            },
        ),
        migrations.CreateModel(
            name='LexemeMeaningMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное значение')),
                ('lexeme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning')),
            ],
            options={
                'verbose_name': 'Связь лемма-смысл',
                'verbose_name_plural': 'Связи лемма-смысл',
            },
        ),
        migrations.AddField(
            model_name='gesturelexemecompose',
            name='meanings',
            field=models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Смыслы'),
        ),
        migrations.AddField(
            model_name='gesturelexeme',
            name='meanings',
            field=models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Смыслы'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TextLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(unique=True)),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква / Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
                ('meanings', models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Смыслы')),
            ],
            options={
                'verbose_name': 'Текстовая лемма',
                'verbose_name_plural': 'Текстовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='TextComposeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.textlexeme')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TextLexemeCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст / Жест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='dictionary.category', verbose_name='Категории')),
                ('items', models.ManyToManyField(related_name='used_in_composes', through='dictionary.TextComposeItem', to='dictionary.textlexeme')),
                ('meanings', models.ManyToManyField(related_name='%(class)s_set', to='dictionary.meaning', verbose_name='Смыслы')),
            ],
            options={
                'verbose_name': 'Сочетание слов',
                'verbose_name_plural': 'Сочетания слов',
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='textcomposeitem',
            name='compose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compose_items', to='dictionary.textlexemecompose'),
        ),
        migrations.AddIndex(
            model_name='gesturecomposeitem',
            index=models.Index(fields=['compose', 'position'], name='dictionary__compose_abfd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturecomposeitem',
            index=models.Index(fields=['gesture_lexeme', 'position'], name='dictionary__gesture_f2c564_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gesturecomposeitem',
            unique_together={('compose', 'position')},
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['text_lexeme_type', 'text_lexeme_id'], name='dictionary__text_le_165ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='lexemepair',
            index=models.Index(fields=['gesture_lexeme_type', 'gesture_lexeme_id'], name='dictionary__gesture_0b5bca_idx'),
        ),
        migrations.AddIndex(
            model_name='lexememeaningmapping',
            index=models.Index(fields=['lexeme_type', 'lexeme_id'], name='dictionary__lexeme__117a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lexememeaningmapping',
            unique_together={('lexeme_type', 'lexeme_id', 'meaning')},
        ),
        migrations.AddIndex(
            model_name='textcomposeitem',
            index=models.Index(fields=['compose', 'position'], name='dictionary__compose_e6d538_idx'),
        ),
        migrations.AddIndex(
            model_name='textcomposeitem',
            index=models.Index(fields=['text_lexeme', 'position'], name='dictionary__text_le_e27719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textcomposeitem',
            unique_together={('compose', 'position')},
        ),
    ]
