# Generated by Django 6.0.3 on 2026-03-06 00:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hearing_status', models.CharField(choices=[('hearing', 'Слышащий'), ('hard_of_hearing', 'Слабослышащий'), ('deaf', 'Глухой')], default='hearing', max_length=20, verbose_name='Статус слуха')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('native', 'Носитель РЖЯ'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GestureLemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='Жестовая лемма')),
                ('situation', models.CharField(blank=True, max_length=100, verbose_name='Ситуация использования')),
                ('emotional_coloring', models.CharField(blank=True, max_length=50, verbose_name='Эмоциональная окраска')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('is_dialectal', models.BooleanField(default=False, verbose_name='Диалектный')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Жест буквы')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antonyms', models.ManyToManyField(blank=True, to='dictionary.gesturelemma', verbose_name='Антонимы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gesture_lemmas', to=settings.AUTH_USER_MODEL)),
                ('related_lemmas', models.ManyToManyField(blank=True, to='dictionary.gesturelemma', verbose_name='Похожие слова')),
                ('synonyms', models.ManyToManyField(blank=True, to='dictionary.gesturelemma', verbose_name='Синонимы')),
            ],
            options={
                'verbose_name': 'Жестовая лемма',
                'verbose_name_plural': 'Жестовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GestureRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная реализация')),
                ('video', models.FileField(upload_to='videos/gestures/', verbose_name='Видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_realizations', to=settings.AUTH_USER_MODEL)),
                ('gesture_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='dictionary.gesturelemma', verbose_name='Жестовая лемма')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_realizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реализация жеста (видео)',
                'verbose_name_plural': 'Реализации жестов (видео)',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание смысла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hypernym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hyponyms', to='dictionary.meaning', verbose_name='Верхнее понятие')),
            ],
            options={
                'verbose_name': 'Смысл (денотат)',
                'verbose_name_plural': 'Смыслы (денотаты)',
            },
        ),
        migrations.CreateModel(
            name='GestureMeaningMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное значение')),
                ('gesture_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gesturelemma')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning')),
            ],
            options={
                'verbose_name': 'Связь жест-смысл',
                'verbose_name_plural': 'Связи жест-смысл',
                'unique_together': {('gesture_lemma', 'meaning')},
            },
        ),
        migrations.AddField(
            model_name='gesturelemma',
            name='meanings',
            field=models.ManyToManyField(related_name='gesture_lemmas', through='dictionary.GestureMeaningMapping', to='dictionary.meaning', verbose_name='Смыслы'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TextLemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='Текстовая лемма')),
                ('slug', models.SlugField(unique=True)),
                ('situation', models.CharField(blank=True, max_length=100, verbose_name='Ситуация использования')),
                ('emotional_coloring', models.CharField(blank=True, max_length=50, verbose_name='Эмоциональная окраска')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('is_dialectal', models.BooleanField(default=False, verbose_name='Диалектный')),
                ('is_letter', models.BooleanField(default=False, verbose_name='Буква алфавита')),
                ('letter_char', models.CharField(blank=True, max_length=1, verbose_name='Символ буквы')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antonyms', models.ManyToManyField(blank=True, to='dictionary.textlemma', verbose_name='Антонимы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_text_lemmas', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='text_lemmas', to='dictionary.category', verbose_name='Категории')),
                ('related_lemmas', models.ManyToManyField(blank=True, to='dictionary.textlemma', verbose_name='Похожие слова')),
                ('synonyms', models.ManyToManyField(blank=True, to='dictionary.textlemma', verbose_name='Синонимы')),
            ],
            options={
                'verbose_name': 'Текстовая лемма',
                'verbose_name_plural': 'Текстовые леммы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='TextMeaningMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное значение')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning')),
                ('text_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Связь текст-смысл',
                'verbose_name_plural': 'Связи текст-смысл',
                'unique_together': {('text_lemma', 'meaning')},
            },
        ),
        migrations.AddField(
            model_name='textlemma',
            name='meanings',
            field=models.ManyToManyField(related_name='text_lemmas', through='dictionary.TextMeaningMapping', to='dictionary.meaning', verbose_name='Смыслы'),
        ),
        migrations.CreateModel(
            name='PersonalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(choices=[(0, 'Не изучено'), (1, 'Начинаю изучать'), (2, 'Знаю плохо'), (3, 'Знаю хорошо'), (4, 'Отлично знаю'), (5, 'Владею в совершенстве')], default=0, verbose_name='Уровень знания')),
                ('practice_count', models.IntegerField(default=0, verbose_name='Количество тренировок')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='Последняя тренировка')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('gesture_lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_personal_dicts', to='dictionary.gesturelemma')),
                ('meaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_dictionary_entries', to='dictionary.meaning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_dictionary', to=settings.AUTH_USER_MODEL)),
                ('text_lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_personal_dicts', to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Запись в личном словаре',
                'verbose_name_plural': 'Личный словарь',
                'constraints': [models.CheckConstraint(condition=models.Q(('text_lemma__isnull', False), ('gesture_lemma__isnull', False), _connector='OR'), name='at_least_one_lemma')],
                'unique_together': {('user', 'text_lemma', 'gesture_lemma', 'meaning')},
            },
        ),
    ]
