# Generated by Django 6.0.2 on 2026-02-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturelemma',
            name='is_letter',
            field=models.BooleanField(default=False, verbose_name='Жест буквы'),
        ),
        migrations.AddField(
            model_name='gesturelemma',
            name='letter_char',
            field=models.CharField(blank=True, max_length=1, verbose_name='Символ буквы'),
        ),
        migrations.AddField(
            model_name='textlemma',
            name='is_letter',
            field=models.BooleanField(default=False, verbose_name='Буква алфавита'),
        ),
        migrations.AddField(
            model_name='textlemma',
            name='letter_char',
            field=models.CharField(blank=True, max_length=1, verbose_name='Символ буквы'),
        ),
    ]
