# Generated by Django 6.0.3 on 2026-03-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlemma',
            options={'ordering': ['text'], 'verbose_name': 'Текстовая лемма', 'verbose_name_plural': 'Текстовые леммы'},
        ),
        migrations.RenameField(
            model_name='textlemma',
            old_name='name',
            new_name='text',
        ),
    ]
