# Generated by Django 6.0.3 on 2026-03-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_meaning_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesturelemma',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='gesturelemma',
            name='related_lemmas',
        ),
        migrations.RemoveField(
            model_name='gesturelemma',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='textlemma',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='textlemma',
            name='related_lemmas',
        ),
        migrations.RemoveField(
            model_name='textlemma',
            name='synonyms',
        ),
    ]
