# Generated by Django 6.0.3 on 2026-03-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_textlemma_options_rename_name_textlemma_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestureexample',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gestureexample',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='gestureexplanation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gestureexplanation',
            name='meaning',
        ),
        migrations.AlterUniqueTogether(
            name='synonymrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='synonymrelation',
            name='from_lemma',
        ),
        migrations.RemoveField(
            model_name='synonymrelation',
            name='to_lemma',
        ),
        migrations.RemoveField(
            model_name='textexample',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textexample',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='textexplanation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textexplanation',
            name='meaning',
        ),
        migrations.RenameField(
            model_name='gesturerealization',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gesturemeaningmapping',
            name='usage_preference_score',
        ),
        migrations.RemoveField(
            model_name='gesturerealization',
            name='execution_notes',
        ),
        migrations.RemoveField(
            model_name='gesturerealization',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='textmeaningmapping',
            name='usage_preference_score',
        ),
        migrations.CreateModel(
            name='GestureAntonymRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_antonym_from', to='dictionary.textlemma')),
                ('to_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_antonym_to', to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Жест. антонимическая связь',
                'verbose_name_plural': 'Жест. антонимические связи',
                'unique_together': {('from_lemma', 'to_lemma')},
            },
        ),
        migrations.CreateModel(
            name='GestureSynonymRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_synonym_from', to='dictionary.gesturelemma')),
                ('to_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_synonym_to', to='dictionary.gesturelemma')),
            ],
            options={
                'verbose_name': 'Жест. синонимическая связь',
                'verbose_name_plural': 'Жест. синонимические связи',
                'unique_together': {('from_lemma', 'to_lemma')},
            },
        ),
        migrations.CreateModel(
            name='TextAntonymRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_antonym_from', to='dictionary.textlemma')),
                ('to_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_antonym_to', to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Текст. антонимическая связь',
                'verbose_name_plural': 'Текст. антонимические связи',
                'unique_together': {('from_lemma', 'to_lemma')},
            },
        ),
        migrations.AlterField(
            model_name='gesturelemma',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='antonyms_rel', through='dictionary.TextAntonymRelation', to='dictionary.gesturelemma', verbose_name='Антонимы'),
        ),
        migrations.AlterField(
            model_name='textlemma',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='antonyms_rel', through='dictionary.TextAntonymRelation', to='dictionary.textlemma', verbose_name='Антонимы'),
        ),
        migrations.CreateModel(
            name='TextSynonymRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_synonym_from', to='dictionary.textlemma')),
                ('to_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_synonym_to', to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Текст. синонимическая связь',
                'verbose_name_plural': 'Текст. синонимические связи',
                'unique_together': {('from_lemma', 'to_lemma')},
            },
        ),
        migrations.AlterField(
            model_name='gesturelemma',
            name='synonyms',
            field=models.ManyToManyField(blank=True, through='dictionary.TextSynonymRelation', to='dictionary.gesturelemma', verbose_name='Синонимы'),
        ),
        migrations.AlterField(
            model_name='textlemma',
            name='synonyms',
            field=models.ManyToManyField(blank=True, through='dictionary.TextSynonymRelation', to='dictionary.textlemma', verbose_name='Синонимы'),
        ),
        migrations.DeleteModel(
            name='AntonymRelation',
        ),
        migrations.DeleteModel(
            name='GestureExample',
        ),
        migrations.DeleteModel(
            name='GestureExplanation',
        ),
        migrations.DeleteModel(
            name='SynonymRelation',
        ),
        migrations.DeleteModel(
            name='TextExample',
        ),
        migrations.DeleteModel(
            name='TextExplanation',
        ),
    ]
