# Generated by Django 6.0.3 on 2026-03-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_gestureexample_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gesturelemma',
            options={'ordering': ['text'], 'verbose_name': 'Жестовая лемма', 'verbose_name_plural': 'Жестовые леммы'},
        ),
        migrations.RenameField(
            model_name='gesturelemma',
            old_name='name',
            new_name='text',
        ),
    ]
