# Generated by Django 6.0.3 on 2026-03-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_gesturelemma_antonyms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturelemma',
            name='categories',
            field=models.ManyToManyField(related_name='gesture_lemmas', to='dictionary.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('native', 'Носитель РЖЯ'), ('linguist', 'Лингвист'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='LexemePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_meaning', models.BooleanField(default=True, help_text='Автоматически созданный смысл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gesture_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_pairs', to='dictionary.gesturelemma')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='dictionary.meaning')),
                ('text_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_pairs', to='dictionary.textlemma')),
            ],
            options={
                'unique_together': {('text_lemma', 'gesture_lemma', 'meaning')},
            },
        ),
    ]
