# Generated by Django 6.0.3 on 2026-03-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_gesturelemma_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesturelemma',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='antonyms_rel', through='dictionary.GestureAntonymRelation', to='dictionary.gesturelemma', verbose_name='Антонимы'),
        ),
        migrations.AlterField(
            model_name='gesturelemma',
            name='synonyms',
            field=models.ManyToManyField(blank=True, through='dictionary.GestureSynonymRelation', to='dictionary.gesturelemma', verbose_name='Синонимы'),
        ),
        migrations.AlterField(
            model_name='textantonymrelation',
            name='from_lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_antonym_from', to='dictionary.gesturelemma'),
        ),
        migrations.AlterField(
            model_name='textantonymrelation',
            name='to_lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_antonym_to', to='dictionary.gesturelemma'),
        ),
    ]
