# Generated by Django 6.0.3 on 2026-03-13 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_gesturelemma_categories_alter_user_role_lexemepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureLemmaCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meanings', models.ManyToManyField(related_name='gesture_composes', to='dictionary.meaning')),
            ],
            options={
                'verbose_name': 'Сочетание жестов',
            },
        ),
        migrations.CreateModel(
            name='TextLemmaCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Фраза')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meanings', models.ManyToManyField(related_name='text_composes', to='dictionary.meaning')),
            ],
            options={
                'verbose_name': 'Сочетание слов',
            },
        ),
        migrations.CreateModel(
            name='GestureComposeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gesturelemma')),
                ('compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dictionary.gesturelemmacompose')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['compose', 'position'], name='dictionary__compose_abfd4e_idx'), models.Index(fields=['lemma', 'position'], name='dictionary__lemma_i_b9aa8a_idx')],
                'unique_together': {('compose', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TextComposeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.textlemma')),
                ('compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dictionary.textlemmacompose')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['compose', 'position'], name='dictionary__compose_e6d538_idx'), models.Index(fields=['lemma', 'position'], name='dictionary__lemma_i_95975a_idx')],
                'unique_together': {('compose', 'position')},
            },
        ),
    ]
