# Generated by Django 6.0.3 on 2026-03-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_gesturelemma_antonyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextGestureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gesture_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_mappings', to='dictionary.gesturelemma')),
                ('text_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_mappings', to='dictionary.textlemma')),
            ],
            options={
                'verbose_name': 'Связь слово-жест',
                'verbose_name_plural': 'Связи слово-жест',
                'unique_together': {('text_lemma', 'gesture_lemma')},
            },
        ),
        migrations.AddField(
            model_name='gesturelemma',
            name='texts',
            field=models.ManyToManyField(related_name='mapped_gestures', related_query_name='gesture', through='dictionary.TextGestureMapping', to='dictionary.textlemma', verbose_name='Слова'),
        ),
        migrations.AddField(
            model_name='textlemma',
            name='gestures',
            field=models.ManyToManyField(related_name='mapped_texts', related_query_name='gesture_text', through='dictionary.TextGestureMapping', to='dictionary.gesturelemma', verbose_name='Жесты'),
        ),
    ]
