from .home import moderation_home
from .text_lexeme import moderation_text_lexeme
from .meaning import moderation_meaning
from .lexeme_triplet import moderation_lexeme_triplet
from .gesture_realization import moderation_gesture_realization