# Generated by Django 6.0.3 on 2026-07-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучаю'), ('learned', 'Выучено')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('lexeme_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexemepair')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
